name: big_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numba
  - numpy
  - pandas
  - pip
  - requests
  - scikit-learn
  - seaborn
  - tqdm
  - pytest
  - pip:
    - beautifulsoup4
    - jupyter
    - matplotlib
    - opencv-python
    - pymongo
    - psycopg2
    - spyder>=5.*
