name: big_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numba
  - numpy
  - pandas
  - pip
  - pytorch
  - scikit-learn
  - torchvision>=0.17
  - tqdm
  - pytest
  - pip:
    - Faker
    - jupyter
    - matplotlib
    - opencv-python
    - pymongo
    - psycopg2
    - scipy
    - seaborn
    - spyder>=5.*
